import { OrganizationRole, Permission } from '../../../types';

export const ROLE_PERMISSIONS: Record<OrganizationRole, Permission[]> = {
  owner: [
    'organizations.read',
    'organizations.update',
    'projects.create',
    'projects.read',
    'projects.update',
    'projects.delete',
    'environments.create',
    'environments.read',
    'environments.update',
    'environments.delete',
    'variables.create',
    'variables.read',
    'variables.update',
    'variables.delete',
    'variables.reveal',
    'variables.export',
    'variables.rotate',
    'variables.sync',
    'imports.preview',
    'imports.run',
    'exports.preview',
    'exports.run',
    'audit.read',
    'members.invite',
    'members.update',
    'members.remove',
    'roles.read',
    'roles.manage',
    'billing.read',
    'billing.manage',
    'integrations.read',
    'integrations.manage',
    'notifications.read',
    'settings.manage',
  ],
  admin: [
    'organizations.read',
    'organizations.update',
    'projects.create',
    'projects.read',
    'projects.update',
    'projects.delete',
    'environments.create',
    'environments.read',
    'environments.update',
    'environments.delete',
    'variables.create',
    'variables.read',
    'variables.update',
    'variables.delete',
    'variables.reveal',
    'variables.export',
    'variables.rotate',
    'variables.sync',
    'imports.preview',
    'imports.run',
    'exports.preview',
    'exports.run',
    'audit.read',
    'members.invite',
    'members.update',
    'members.remove',
    'roles.read',
    'integrations.read',
    'integrations.manage',
    'notifications.read',
    'settings.manage',
  ],
  devops: [
    'organizations.read',
    'projects.create',
    'projects.read',
    'projects.update',
    'environments.create',
    'environments.read',
    'environments.update',
    'variables.create',
    'variables.read',
    'variables.update',
    'variables.reveal',
    'variables.export',
    'variables.rotate',
    'variables.sync',
    'imports.preview',
    'imports.run',
    'exports.preview',
    'exports.run',
    'audit.read',
    'integrations.read',
    'integrations.manage',
    'notifications.read',
  ],
  developer: [
    'organizations.read',
    'projects.read',
    'projects.update',
    'environments.read',
    'variables.create',
    'variables.read',
    'variables.update',
    'variables.reveal',
    'imports.preview',
    'imports.run',
    'exports.preview',
    'notifications.read',
  ],
  viewer: [
    'organizations.read',
    'projects.read',
    'environments.read',
    'variables.read',
    'notifications.read',
  ],
  auditor: [
    'organizations.read',
    'projects.read',
    'environments.read',
    'variables.read',
    'audit.read',
    'notifications.read',
  ],
};

export const getPermissionsForRoles = (roles: OrganizationRole[]): Permission[] => {
  return [...new Set(roles.flatMap((role) => ROLE_PERMISSIONS[role] ?? []))];
};

export const hasPermission = (
  permissions: Permission[] | undefined,
  permission: Permission,
) => permissions?.includes(permission) ?? false;
